In [92]:
    import os
    import sys
    import numpy as np
    import pandas as pd
    import sklearn.preprocessing as pp
    from sklearn.cross_validation import train_test_split
    from sklearn import svm, linear_model, naive_bayes
    import simplejson as json
    from sklearn.model_selection import GridSearchCV
    from sklearn.pipeline import make_union, make_pipeline
    from sklearn.preprocessing import FunctionTransformer
    from sklearn.base import BaseEstimator, TransformerMixin

    # from https://medium.com/@literallywords/sklearn-identity-transformer-fcc18bac0e98
    class IdentityTransformer(BaseEstimator, TransformerMixin):
        def __init__(self):
            pass

        def fit(self, input_array, y=None):
            return self

        def transform(self, input_array, y=None):
            return input_array * 1

    # Get training data
    df = pd.read_csv('pima-data.csv')
    
    float_formatter = lambda x: "%.2f" % x
    np.set_printoptions(formatter={'float_kind':float_formatter})
    
    feature_col_names_fullset = ['num_preg', 'glucose_conc', 'diastolic_bp', 'thickness', 'insulin', 'bmi', 'diab_pred', 'age']
    feature_col_names = ['num_preg', 'glucose_conc', 'bmi', 'diab_pred', 'age']
    predicted_class_names = ['diabetes']
    
    x = df[feature_col_names].values
    y = df[predicted_class_names].values
    
    fill_0 = pp.Imputer(missing_values=0, strategy="mean", axis=0)
    scaler = pp.StandardScaler()
    
    def get_invalid0_cols(df):
        return df[['glucose_conc', 'bmi', 'diab_pred','age']]

    def get_valid0_cols(df):
        return df[['num_preg']]

    vec = make_union(*[
        make_pipeline(FunctionTransformer(get_valid0_cols, validate=False), IdentityTransformer()),
        make_pipeline(FunctionTransformer(get_invalid0_cols, validate=False), fill_0),
        #make_pipeline(FunctionTransformer(get_num_cols, validate=False), scaler)
    ])
    
    x = vec.fit_transform(df)
    #x = scaler.fit_transform(x)
    
    split_test_size = 0.20
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=split_test_size, random_state=73) 
    
    

[[6.00 148.00 33.60 0.63 50.00]
 [1.00 85.00 26.60 0.35 31.00]
 [8.00 183.00 23.30 0.67 32.00]
 [1.00 89.00 28.10 0.17 21.00]
 [0.00 137.00 43.10 2.29 33.00]
 [5.00 116.00 25.60 0.20 30.00]
 [3.00 78.00 31.00 0.25 26.00]
 [10.00 115.00 35.30 0.13 29.00]
 [2.00 197.00 30.50 0.16 53.00]
 [8.00 125.00 32.46 0.23 54.00]]
